# {name} - Bukkit Plugin configuration file

name: {name}
main: {bukkit.main.class}
version: {plugin.version}
author: Visual Illusions Entertainment
website: {wiki}
depend: [dConomy]

# Visual Illusions Specific Stuff
developers: {devs}
build.number: {build}
build.time: {build.time}
program.status: {program.status}
check.url: {version.check.url}
issues.url: {issues}
copyright.years: {copyright.years}
# # #

commands:
  bank:
    description: Bank base command, Displays bank balance.
    usage: /bank [sub] [args]
    permission: dconomy.bank.base
  bank deposit:
    description: Used to deposit into the bank
    usage: /bank deposit <amount>
    permission: dconomy.bank.deposit
  bank withdraw:
    description: Used to withdraw from the bank
    usage: /bank withdraw <amount>
    permission: dconomy.bank.withdraw
  bank add:
    description: Adds money to a User's bank
    usage: /bank add <amount> <user>
    permission: dconomy.admin.bank.add
  bank remove:
    description: Removes money from a User's bank
    usage: /bank remove <amount> <user>
    permission: dconomy.admin.bank.remove
  bank set:
    description: Sets the money in a User's bank
    usage: /bank set <amount> <user>
    permission: dconomy.admin.bank.set
  bank reset:
    description: Resets the money in a User's bank
    permission: dconomy.admin.bank.reset
  bank reload:
    description: Reloads a User's bank from the datasource
    permissions: dconomy.admin.bank.reload
  bank lock:
    description: Locks/Unlocks a User's bank
    permissions: dconomy.admin.bank.lock
  dbanklite:
    description: Displays build info about dBankLite and a few other things.
    usage: /dBankLite

permissions:
  dconomy.bank.*:
    description: Gives access to all Bank commands (except administration)
    default: op
    children:
      dconomy.bank.base: true
      dconomy.bank.deposit: true
  dconomy.bank.base:
    description: Give access to bank base command.
    default: op
  dconomy.bank.deposit:
    description: Give access to bank pay command.
    default: op
  dconomy.admin.bank.*:
    description: Gives Admin rights to all dBankLite Bank Accounts
    default: op
    children:
      dconomy.admin.bank.add: true
      dconomy.admin.bank.remove: true
      dconomy.admin.bank.set: true
      dconomy.admin.bank.reset: true
      dconomy.admin.bank.reload: true
      dconomy.admin.bank.lock: true
  dconomy.admin.bank.add:
    description: Gives rights to add money to a bank
    default: op
  dconomy.admin.bank.remove:
    description: Gives rights to remove money from a bank
    default: op
  dconomy.admin.bank.set:
    description: Gives rights to set the money in a bank
    default: op
  dconomy.admin.bank.reset:
    description: Gives rights to reset the money in a bank
    default: op
  dconomy.admin.bank.reload:
    description: Gives rights to reload a User's Bank account
    default: op
  dconomy.admin.bank.lock:
    description: Gives rights to lock/unlock a User's Bank account
    default: op

#
#  This file is part of {name}.
#
#  Copyright © {copyright.years} Visual Illusions Entertainment.
#
#  {name} is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  {name} is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with {name}.
#  If not, see http://www.gnu.org/licenses/gpl.html
#